"""Reviewed task recipes: route roles are explicit, never selected by catalogue order."""

def routes(prefix, **roles):
    return {key: ['/api/v1/' + prefix + '/' + leaf for leaf in value.split()] for key, value in roles.items()}


PLATFORMS = {
    'douyin': routes('douyin',
        search='search/fetch_video_search_v5', users='search/fetch_user_search_v2',
        profile='web/handler_user_profile', posts='web/fetch_user_post_videos',
        detail='web/fetch_one_video', comments='web/fetch_video_comments web/fetch_video_comment_replies',
        hot='web/fetch_hot_search_result billboard/fetch_hot_total_video_list',
        growth='billboard/fetch_hot_item_trends_list billboard/fetch_hot_account_trends_list',
        candidates='billboard/fetch_hot_account_list',
        live='search/fetch_live_search_v2 web/fetch_user_live_info_by_uid'),
    'tiktok': routes('tiktok',
        search='app/v3/fetch_video_search_result', users='app/v3/fetch_user_search_result',
        profile='app/v3/handler_user_profile', posts='app/v3/fetch_user_post_videos',
        detail='app/v3/fetch_one_video', comments='app/v3/fetch_video_comments app/v3/fetch_video_comment_replies',
        hot='web/fetch_trending_searchwords',
        hashtag='app/v3/fetch_hashtag_search_result app/v3/fetch_hashtag_detail app/v3/fetch_hashtag_video_list'),
    'xiaohongshu': routes('xiaohongshu',
        search='app_v2/search_notes', users='app_v2/search_users',
        profile='app_v2/get_user_info', posts='app_v2/get_user_posted_notes',
        detail='app_v2/get_image_note_detail app_v2/get_video_note_detail',
        comments='app_v2/get_note_comments app_v2/get_note_sub_comments',
        similar='pgy/get_blogger_similar', growth='pgy/get_blogger_fans_history',
        inspiration='app_v2/get_creator_hot_inspiration_feed'),
    'wechat': routes('wechat_mp/v2',
        search='fetch_article_detail', profile='fetch_account_profile', posts='fetch_account_articles',
        detail='fetch_article_detail', stats='fetch_article_stats',
        comments='fetch_article_comments fetch_comment_replies', similar='fetch_related_articles'),
    'wechat-channels': routes('wechat_channels/v2',
        profile='fetch_user_profile', posts='fetch_user_videos',
        detail='fetch_video_detail', comments='fetch_video_comments',
        media='fetch_video_detail fetch_video_share_url'),
    'bilibili': routes('bilibili',
        search='web/fetch_general_search', users='app/fetch_search_by_type',
        profile='web/fetch_user_profile', posts='web/fetch_user_post_videos_v2',
        detail='web/fetch_video_detail', comments='web/fetch_video_comments web/fetch_comment_reply',
        hot='web/fetch_hot_search', media='web/fetch_video_playurl'),
    'kuaishou': routes('kuaishou',
        search='app/search_video_v2', users='app/search_user_v2', profile='web/fetch_user_info',
        posts='app/fetch_user_post_v2', detail='web/fetch_one_video',
        comments='app/fetch_video_comment app/fetch_video_sub_comments',
        hot='web/fetch_kuaishou_hot_list_v2', live='app/search_live app/fetch_user_live_info'),
    'weibo': routes('weibo/web_v2',
        search='fetch_realtime_search', users='fetch_user_search', profile='fetch_user_info',
        posts='fetch_user_posts', detail='fetch_post_detail',
        comments='fetch_post_comments fetch_post_sub_comments', hot='fetch_hot_search'),
    'x': routes('twitter/web',
        search='fetch_search_timeline', profile='fetch_user_profile', posts='fetch_user_post_tweet',
        detail='fetch_tweet_detail', comments='fetch_post_comments fetch_latest_post_comments', hot='fetch_trending'),
    'youtube': routes('youtube/web_v2',
        search='get_general_search_v2', users='search_channels', profile='get_channel_description',
        posts='get_channel_videos', detail='get_video_info',
        comments='get_video_comments get_video_comment_replies',
        media='get_video_streams_v2 get_signed_stream_url',
        transcript='get_video_captions get_video_captions_result'),
    'instagram': routes('instagram/v3',
        users='search_users', profile='get_user_profile', posts='get_user_posts',
        detail='get_post_info_by_code', comments='get_post_comments get_comment_replies',
        hashtag='search_hashtags get_hashtag_posts'),
    'reddit': routes('reddit/app',
        search='fetch_dynamic_search', profile='fetch_user_profile', posts='fetch_user_posts',
        detail='fetch_post_details', comments='fetch_post_comments fetch_comment_replies',
        community='fetch_subreddit_info fetch_subreddit_feed', hot='fetch_trending_searches'),
    'zhihu': routes('zhihu/web',
        search='fetch_article_search_v3', users='fetch_user_search_v3', profile='fetch_user_info',
        posts='fetch_user_answers fetch_user_articles', detail='fetch_answer_detail',
        question='fetch_question_detail fetch_question_answers', comments='fetch_comment_v5', hot='fetch_hot_list'),
    'toutiao': {'profile': ['/api/v1/toutiao/app/get_user_info'], 'detail': ['/api/v1/toutiao/web/get_article_info'], 'comments': ['/api/v1/toutiao/app/get_comments']},
}
PLATFORMS['wechat']['search'] = ['/api/v1/wechat_search/v2/fetch_search']
PLATFORMS['instagram']['search'] = ['/api/v1/instagram/v2/search_reels']
PLATFORMS['wechat-channels']['search'] = ['/api/v1/wechat_search/v2/fetch_search_videos']

ALIASES = {
    'x-subscribe': 'x-account-brief', 'x-entrepreneur-rank': 'x-candidate-research',
    'x-top-account': 'x-candidate-research', 'gzh-toutiao-growth-rank': 'wechat-fastest-growing',
    'gzh-search-crawler': 'gzh-search', 'xiaohongshu-creator': 'xiaohongshu-write',
    'wechat-creator': 'wechat-write', 'global-ai-news-brief': 'multi-content-feed',
    'weibo-comment-search': 'weibo-comment', 'weibo-realtime-search': 'weibo-search',
    'weibo-hot-search': 'weibo-hot-topic-radar', 'weibo-post-search': 'weibo-account-monitor',
    'tiktok-home-downloader': 'tiktok-video-downloader', 'wechat-channels-crawler': 'wechat-channel-brief',
    'wecht-copywrite-alchemy': 'wechat-reference-rewrite',
    'multi-copywrite-alchemy': 'multi-reference-rewrite',
    'douyin-copywrite-alchemy': 'douyin-reference-rewrite',
    'kuaishou-ai-feed': 'ks-ai-feed', 'bilibili-ai-feed': 'bili-ai-feed',
    'xhs-title-scorer': 'xiaohongshu-title-score',
    'bilibili-keyword-account': 'bilibili-keywords-accounts',
    'xiaohongshu-inspiration': 'xiaohongshu-inspiration',
    'multi-rewrite': 'multi-reference-rewrite', 'wechat-rewrite': 'wechat-reference-rewrite',
    'xiaohongshu-rewrite': 'xiaohongshu-reference-rewrite', 'zhihu-rewrite': 'zhihu-reference-rewrite',
    'kuaishou-video-extract': 'kuaishou-caption-extract',
    'twitter-video-downloader': 'x-video-extract',
}
UNSUPPORTED = {
    'image-gen': '未注册 GPT-image2 图片生成接口。',
    'visual-ops-writer': '图文创作中的图片生成功能没有注册接口；文字创作可用各平台写作 Skill。',
    'pdf-image-text-extractor': '未注册 PDF 解析或 OCR 接口。',
    'gzh-astock-top': '没有可信 A 股大 V 榜单来源；公众号搜索不等于股票权威排名。',
    'stock-analysis': '没有行情、交易与财报接口，无法完成该股票分析契约。',
    'investor-distiller': '缺少投资策略与历史收益验证数据；不能把文章风格分析包装为策略验证。',
    'geo-analyzer': '没有多模型答案采样、搜索引擎排名或品牌引用评估接口。',
    'wechat-cover': '未注册图片生成接口；不能生成实际封面文件。',
    'xiaohongshu-cover': '未注册图片生成接口；该旧入口下线，文字选题不等于封面生成。',
    'ai-intelligence-investigator': '缺少行情、上市公司公告与金融数据核验接口。',
    'redfox-skill-generator': '第三方平台的 Skill 生成服务未注册；本仓库提供本地生成维护工具。',
    'kimi-websearch': '未注册 Kimi 搜索接口。',
    'video-prompt-expert': '没有 Seedance 提示词验证与生成接口；模型专用效果无法验证。',
    'multi-wordcheck': '没有平台权威违禁词库或审核接口，不能提供该检测能力。',
    'deepseek-websearch': '未注册 Deepseek 搜索接口。',
    'toutiao-search': '最新版 TikHub 的今日头条没有关键词搜索接口；保留链接文章解析替代项。',
    'stock-feed': '没有股市行情及官方公告数据源；社交帖子不等于金融新闻核验。',
    'doubao-websearch': '未注册豆包搜索接口。',
    'seedream-5-lite': '未注册 Seedream 图片生成接口。',
    'seedance-video-gen': '未注册 Seedance 视频生成接口。',
    'optimize-skill-md': '不属于已注册数据 API 能力，本仓库维护指南覆盖静态校验。',
    'douyin-prohibited-word': '没有抖音官方词库或内容审核接口。',
    'wechat-prohibited-word': '没有微信官方词库或内容审核接口。',
    'xiaohongshu-prohibited-word': '没有小红书官方词库或内容审核接口。',
}

WORKFLOWS = {
    'search': ('关键词检索', ['把关键词、地区、语言、时间窗口与结果数量分开确认。只把契约中存在的字段写入请求。', '先查询一页，读取实际结果集合与分页字段。内容详情不足时，按真实 ID 调用详情接口。', '按内容 ID 去重；有发布时间则按用户窗口过滤，没有时间则列入未知时间组。', '按用户指定且返回中存在的指标排序。输出原始指标、链接、采集时间和样本范围，禁止叫作平台全量榜单。'], '内容ID、标题、作者、发布时间、实际互动指标、来源链接、与关键词相关性'),
    'feed': ('主题信息源', ['确定主题、受众、语言和采样窗口；AI、文旅、短剧等主题采用用户确认的关键词组合。', '对每个关键词查询一页；最多三个关键词。优先按平台内作品 ID 去重，跨平台同一事件聚类但保留出处。', '挑选有正文或描述支撑的内容，必要时查询详情；区分事实摘要、作者观点和模型推断。', '给出主题摘要、值得跟进的三个信号和后续选题；数据缺失时列出缺口，不补造播放量或趋势。'], '主题、事实摘要、内容链接、作者、发布时间、采集时间、证据、后续选题'),
    'profile': ('账号诊断', ['确认账号唯一 ID 或用户名；同名账号必须让用户选择正确对象，不能直接采用首条搜索结果。', '读取账号信息和最多三页作品，保留每条内容的采集时间；两个账号对标时使用相同时间窗口。', '计算样本发布频次、互动中位数与内容类型分布；分母缺失则不算互动率。粉丝数不等于曝光或购买力。', '输出定位、表现、三条可执行改进建议与证据；账号潜力属于样本分析，禁止保证涨粉或商业收益。'], '账号ID、定位、样本量、时间窗口、粉丝数（若有）、互动中位数、证据链接、建议'),
    'similar': ('相似账号发现', ['明确目标账号、细分赛道与候选数量。先核验目标账号身份与代表作品。', '有相似推荐接口时先获取推荐候选；否则用目标账号的主题词检索候选账号，明确为搜索候选。', '逐个读取候选资料和最多一页作品，比较主题、形式、频次和受众线索；只使用实际返回字段。', '输出相似理由、差异、匹配依据和候选链接；没有受众画像时不能声明受众重合率。'], '目标账号、候选账号ID、相似理由、差异、样本作品链接、数据缺口'),
    'tracking': ('账号订阅快照', ['确认要跟踪的账号及采样频率；本 Skill 仅执行一次采样。持续订阅需要用户另行配置调度器。', '读取账号与近期作品，在用户指定目录保存脱敏快照：账号ID、内容ID、发布时间、采集UTC时间、存在的指标。', '若用户提供前次快照，按账号ID和内容ID匹配，计算新增内容与同一指标的差值；首次运行只能建立基线。', '输出本次新增作品、变化与缺失项；两次采集间隔不同则分别注明，不把删除或缺失当作下降。'], '采集UTC时间、账号ID、新内容ID、基线时间、当前指标、差值、缺失项'),
    'growth': ('增长样本分析', ['确定内容或账号对象、时间窗口和增长指标；点赞增量、粉丝增量、阅读增量必须分开。', '优先读取该指标的已注册趋势接口。无对应历史接口时，要求同对象两个带UTC时间的快照；首次采样只记录基线。', '增量=current-previous；增长率=增量/previous，previous为0时只报告增量。仅比较同指标、同时间窗、同口径。', '按有效增量在样本内排序；不同时间间隔不能混排，不得将累计点赞或阅读数称为每日飙升。'], '对象ID、指标、前值、后值、前后采集时间、增量、增长率或不可计算原因、样本排名'),
    'hot': ('平台热榜', ['确认平台和榜单类型；有地区、分类等参数时采用该接口支持的枚举。', '获取真实榜单并保留原始排名、热度单位与采集时间；内容详情按需补充，不重写为另一种排行榜。', '合并多个平台时保留各自原排名；不同热度单位不直接相加。聚合Top10采用明确的编辑选择或平台轮换规则。', '输出榜单名称、采集时间、来源、排名与内容摘要；没有官方榜单的赛道只标为关键词样本。'], '平台、榜单名、原始排名、热度及单位（若有）、标题、内容链接、采集时间'),
    'ranking': ('内容样本排名', ['确认时间窗口、关键词与排序指标；每日/七日仅指发布时间筛选，不代表平台官方全量榜。', '从关键词搜索采样，读取实际发布时间与指标；过滤指定窗口，去重并保留未知时间项。', '低粉爆款任务需进一步查询作者粉丝数，明确用户指定的粉丝上限；缺少粉丝数的作者不进入低粉筛选结果。', '按实际指标在样本内排序，列出覆盖量、时间界限和漏采限制；不返回未经数据支持的全网第一。'], '样本排名、内容ID、发布时间、排序指标、作者粉丝数（低粉任务）、链接、覆盖量'),
    'comments': ('评论洞察', ['确认作品ID、分析目标、语言与评论采样数；评论与弹幕不是同一数据源。', '取一页评论；需要上下文时获取对应回复。最多三页，按评论ID去重，保留排序方式和采样范围。', '按需求、问题、支持、反对与其他主题编码；将情绪分类标为模型判断，列出短证据与反例。', '输出主题频次、典型问题、建议回应和样本偏差；比例分母只能为采集样本，不能推断平台全体用户。'], '作品ID、评论样本数、主题、样本频次、情绪判断、短证据、回应建议、样本偏差'),
    'writing': ('参考内容创作', ['确认受众、主题、发布平台、篇幅和用户提供的事实；先阅读用户原稿，缺少事实不自行补充。', '只在用户需要参考时搜索同主题内容并读取少量详情，提取结构、切入角度和读者问题，不复制原文。', '生成原创提纲、正文和候选标题，注明引用与模型建议；标题不编造效果、价格、收益或个人经历。', '输出事实核对清单与修改理由；发布仍由用户完成，本 Skill 不调用发布接口，也不承诺流量。'], '创作简报、参考链接、原创提纲、正文、标题候选、事实核对清单、修改理由'),
    'scoring': ('标题与内容评估', ['获取用户标题/原稿、主题、目标受众和约束。没有原稿或目标内容则先补齐，不凭关键词给出诊断。', '必要时检索同主题样本，对照主题清晰度、受众关联、信息具体度、可读性与事实准确度。', '每维按0至5分评分并说明依据；总分转换为百分制。分数是明确规则下的编辑判断，不是平台流量预测。', '提供三个原创标题或改写方案，保留原意，并分别说明改变及不可核验的陈述。'], '原稿、五维评分、评分理由、事实缺口、三个候选、修改对照'),
    'media': ('媒体信息提取', ['确认作品或账号，限定提取数量与用途；账号主页任务先分页获取作品ID，单作品任务直接查详情。', '只调用绑定的详情或流地址接口，提取响应确实提供的播放地址、封面、格式、时长及有效期。', '视频号需依据真实响应注明是否加密；B站或YouTube音视频可能分离。缺少地址、解密或合并能力时报告状态，不虚构无水印文件。', '输出媒体清单和原始作品链接。本调用器不会请求CDN、下载二进制、解密或合并文件；需要下载时用户另行选择工具并确认权限。'], '作品ID、原始链接、媒体地址（若有）、格式、时长、过期/加密/分流限制、提取状态'),
    'transcript': ('现有字幕与描述提取', ['确认作品ID与目标语言；区分字幕、作品描述和文章正文。', '有字幕接口时发起查询并按契约读取任务结果；异步任务只在用户预算内显式轮询。否则读取描述文本。', '保留语言、时间段与来源；没有字幕就标注缺失，不能把标题或模型推测称为完整转写。', '输出原有字幕摘要或描述摘要、关键点与出处。本 Skill 没有音频ASR能力。'], '作品ID、文本来源类型、语言、已有字幕时间段、摘要、出处、缺失说明'),
    'live': ('直播信息侦察', ['确认平台、主播或关键词以及查询时间；历史回放和正在直播分别记录。', '用直播搜索或主播直播信息接口取样，并保留房间ID、主播、开播状态与返回指标。', '只在接口明确返回商品、价格或带货统计时分析电商信息；在线人数不推算成交额或收入。', '输出房间状态、可核验线索和下一步采样建议；无GMV/成交字段则声明电商结论不可验证。'], '房间ID、主播、开播状态、采集时间、已返回指标、商品信息（若有）、证据、缺口'),
    'community': ('社群与问题研究', ['确认子版块、问题ID或关键词及研究目标；跨社群比较需要相同窗口与样本量。', '读取社群/问题信息及帖子/回答列表，必要时补充评论，保留ID与原始链接。', '按痛点、现有方案、未满足需求和反例归纳；互动数只作样本信号，不代表总体需求规模。', '输出需求假设、支持与反对证据、可以验证的下一步；结论均标注样本范围。'], '社群或问题ID、帖子/回答样本量、需求假设、支持证据、反例、下一步验证'),
    'hashtag': ('话题标签研究', ['确认标签文本或话题ID；文本检索结果与话题ID需明确区分。', '先搜索/核验标签，再读取话题详情与作品列表；ID从实际结果中取，分页游标原样传递。', '统计样本主题和表现，有历史快照才计算涨幅；单次累计量不能声明飙升。', '输出话题ID、详情、样本作品、互动数据与选题建议，说明国家/语言及采样限制。'], '标签ID、标签名、样本作品ID、发布时间、实际指标、链接、采集时间、选题'),
}
